#pragma once

#define UNICODE_SELECTED_MODES UC_LNX
#define DYNAMIC_MACRO_NO_NESTING
#define FORCE_NKRO
#define TAP_CODE_DELAY          10
#define USB_POLLING_INTERVAL_MS 1
#define RGB_MATRIX_STARTUP_SPD  127
#define RGB_MATRIX_KEYPRESSES
