#pragma once

#define UNICODE_SELECTED_MODES UC_LNX
#define DYNAMIC_MACRO_NO_NESTING
#define FORCE_NKRO
#define TAP_CODE_DELAY          10
#define USB_POLLING_INTERVAL_MS 1
#define RGB_MATRIX_STARTUP_SPD  127
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define VIA_CUSTOM_LIGHTING_ENABLE

#define MINUTES             (60 * 1000)
#define RGB_IDLE_TIMEOUT    (5 * MINUTES)
#define RGB_DISABLE_TIMEOUT RGB_IDLE_TIMEOUT

#undef DEBOUNCE
#define DEBOUNCE 2

#include "rgb.h"
