VIA_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
COMMAND_ENABLE = yes
CONSOLE_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
RAW_ENABLE = yes

DEBOUNCE_TYPE = sym_eager_pk
