name: build
on: [push]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cd hidd && ./make.sh

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - run: bash.exe -c 'cd hidd && ./make.sh'
