name: build
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - run: sudo pacman -Syu --noconfirm libusb hidapi alsa-lib pkg-config git

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: compile
        run: cd hidd && ./make.sh

      - uses: actions/upload-artifact@v2
        with:
          name: linux-binary
          path: hidd/hid
          if-no-files-found: error

  windows:
    runs-on: windows-latest
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            pactoys

      - name: compile
        shell: msys2 {0}
        run: |
          pacboy -S --noconfirm toolchain:x libusb:x hidapi:x make:x

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - shell: msys2 {0}
        run: |
          cd hidd && ./make.sh
