name: build
on: [push]
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0-0-dev libhidapi-hidraw0 libhidapi-dev pkg-config libasound2-dev

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: cd hidd
      - run: ./make.sh

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - run: bash.exe -c 'cd hidd && ./make.sh'
