name: build
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0-0-dev libhidapi-hidraw0 libhidapi-dev pkg-config libasound2-dev

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: cd hidd && ./make.sh

  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          release: false

      - shell: msys2 {0}
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-libusb mingw-w64-hidapi mingw-w64-pkg-config mingw-w64-make
          cd hidd && ./make.sh
