name: hidd
on:
  push:
    paths:
      - 'hidd/**'
      - '.github/**'

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: install deps
        run: sudo pacman -Syu --noconfirm libusb hidapi alsa-lib git

      - name: clone
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: compile
        run: cd hidd && ./make.sh

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hid-linux
          path: hidd/hid
          if-no-files-found: error

  windows:
    runs-on: windows-latest
    steps:
      - name: msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            pactoys

      - name: install deps
        shell: msys2 {0}
        run: |
          pacboy -S --noconfirm toolchain:x libusb:x hidapi:x make:x

      - name: clone
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: compile
        shell: msys2 {0}
        run: |
          cd hidd && ./make.sh

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hid-windows
          path: hidd/hid.exe
          if-no-files-found: error
