name: hidd
on:
  push:
    paths:
      - 'hidd/**'
      - '.github/**'

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: format
        uses: jidicula/clang-format-action@v4.2.0
        with:
          clang-format-version: '13'
          check-path: 'hidd'

  linux:
    needs: format
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: install deps
        run: sudo pacman -Syu --noconfirm libusb hidapi alsa-lib git

      - name: clone
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: compile
        run: cd hidd && ./make.sh

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hid-linux
          path: hidd/hid
          if-no-files-found: error

  windows:
    needs: format
    runs-on: windows-latest
    steps:
      - name: msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            pactoys

      - name: install deps
        shell: msys2 {0}
        run: |
          pacboy -S --noconfirm toolchain:x libusb:x hidapi:x make:x

      - name: clone
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: compile
        shell: msys2 {0}
        run: |
          cd hidd && ./make.sh

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hid-windows
          path: hidd/hid.exe
          if-no-files-found: error

  release:
    if: github.ref == 'refs/heads/main'
    needs: [linux, windows]
    runs-on: ubuntu-latest
    steps:
      - name: download linux binary
        uses: actions/download-artifact@v2
        with:
          name: hid-linux

      - name: download windows binary
        uses: actions/download-artifact@v2
        with:
          name: hid-windows

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          name: "latest"
          tag_name: "latest"
          files: |
            *
